### ISSUE TITLE
不能用了噢

### ISSUE THREAD

**Issue by zengruipan** [zy445566/vscode-plugin-btc-market#1]
huobi.pro的接口是不是不行了

**Comment by zy445566** [comment]
> huobi.pro的接口是不是不行了

可以设置扩展的请求地址，如果你没有设置翻墙可以设置请求地址为 huobi.be 就好，然后重启vscode，你试试看？

**Comment by zengruipan** [comment]
好的 可以用了 建议把默认的接口请求地址改成huobi.be

**Comment by zy445566** [comment]
> 好的 可以用了 建议把默认的接口请求地址改成huobi.be

怎么说呢，因为火币的国内域名因为防止国内墙就经常会变，比如huobi.be过段时间就会注销重新生成一个。而huobi.pro是官方认定的不会注销的，所以如果这次改huobi.be可能过两天就不行了，又得改。所以目前没有好的办法，就维持官方认定的huobi. pro了

**Comment by zy445566** [comment]
> huobi.pro的接口是不是不行了

刚刚查了下，好像pro确实完全不能用了，已经改成默认be了，谢谢反馈
那问题解决了，关闭issue了
